name: EZBlocks
main: me.clip.ezblocks.EZBlocks
version: '${project.version}'
author: extended_clip
description: Count players blocks broken
softdepend: [TokenEnchant, AutoSell]
permissions:
    ezblocks.check:
        description: access to check others blocks broken by command
        default: op
    ezblocks.pickaxecounter:
        description: ability to have a pickaxe counter
        default: op
    ezblocks.admin:
        description: access to admin commands
        default: op
commands:
   ezblocks:
     description: EZBlocks main command
     aliases: [blocks]
     